=== Mestre-Tramador/.github/data/labels/conf/labels.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation>
    <xs:appinfo>
      Mestre-Tramador-GitHub-Labels
    </xs:appinfo>

    <xs:documentation>
      This schema determines the rules for XML parsing of
      the reference of the GitHub labels used by Mestre-Tramador.
    </xs:documentation>
  </xs:annotation>

  <xs:element name="labels" type="labels">
    <xs:annotation>
      <xs:documentation>
        The current list of unique labels being used.
      </xs:documentation>
    </xs:annotation>

    <xs:unique name="uniqueLabelName">
      <xs:selector xpath="label" />
      <xs:field xpath="@name" />
    </xs:unique>
  </xs:element>

  <xs:complexType name="labels">
    <xs:annotation>
      <xs:documentation>
        The list of labels is composed solely of labels.
      </xs:documentation>
    </xs:annotation>

    <xs:sequence>
      <xs:element name="label" type="label" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="label">
    <xs:annotation>
      <xs:documentation>
        A GitHub label is mandatorily composed of a name and a color,
        with an additional description.
      </xs:documentation>
    </xs:annotation>

    <xs:attribute name="name" type="labelName" use="required" />
    <xs:attribute name="color" type="labelColor" use="required" />
    <xs:attribute name="description" type="labelDescription" use="optional" />
  </xs:complexType>

  <xs:simpleType name="labelName">
    <xs:annotation>
      <xs:documentation>
        Name of the label.
      </xs:documentation>
    </xs:annotation>

    <xs:restriction base="xs:string">
      <xs:minLength value="1" />
      <xs:maxLength value="50" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="labelColor">
    <xs:annotation>
      <xs:documentation>
        Hexadecimal code of the label color.
      </xs:documentation>
    </xs:annotation>

    <xs:restriction base="xs:string">
      <xs:length value="7" />
      <xs:pattern value="#[A-F0-9]+" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="labelDescription">
    <xs:annotation>
      <xs:documentation>
        A helpful description of the meaning of this label.
      </xs:documentation>
    </xs:annotation>

    <xs:restriction base="xs:string" />
  </xs:simpleType>
</xs:schema>

=== Mestre-Tramador/.github/data/labels/labels.xml
<?xml version="1.0" encoding="UTF-8" ?>
<labels
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="conf/labels.xsd"
>
  <label
    name="Priority: Critical"
    color="#5E0217"
    description="Issue has critical impact on breaking changes and must be implemented at once."
  />

  <label
    name="Priority: High"
    color="#500A00"
    description="Issue has high impact on changes and will be implemented before reaching breaking point."
  />

  <label
    name="Priority: Medium"
    color="#924100"
    description="Issue has medium impact on changes and needs to be implemented in parallel."
  />

  <label
    name="Priority: Low"
    color="#0D3024"
    description="Issue has low impact on changes and can be implemented on normal schedule."
  />

  <label
    name="Status: Open"
    color="#26EDE2"
    description="Issue is open and needs to be reviewed."
  />

  <label
    name="Status: Working"
    color="#88B80F"
    description="Issue is being worked on."
  />

  <label
    name="Status: Resolved"
    color="#F4DA38"
    description="Issue is resolved and will be released on next commit."
  />

  <label
    name="Status: Abandoned"
    color="#0E022C"
    description="Issue is abandoned after being worked on due to a reason."
  />

  <label
    name="Status: Delayed"
    color="#000839"
    description="Issue is delayed due to a reason."
  />

  <label
    name="Status: Closed"
    color="#060907"
    description="Issue is closed and won't be worked on due to a reason."
  />

  <label
    name="Type: Generic Issue"
    color="#08872B"
    description="Issue has been created with generic purpose."
  />

  <label
    name="Type: Bug Report"
    color="#A22710"
    description="Issue has been created or serves as a report of a bug."
  />

  <label
    name="Type: Documentation Revision"
    color="#BE7D00"
    description="Issue has been created or serves as a revision of documentation."
  />

  <label
    name="Type: Feature Request"
    color="#A665F9"
    description="Issue has been created or serves as a request for a feature."
  />
</labels>
